package br.com.mariojp.blog.util;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;

import br.com.mariojp.blog.model.Usuario;

public class Database {

	private Connection connection = null;

	private static Database instance = null;

	private Database() {
		start();
		createDatabase();
	}
	
	
	public static Database getInstance() {
		if(instance == null ) {
			instance = new Database();
		}
		return instance;
	}

	private void start() {
		try {
			Class.forName("org.hsqldb.jdbc.JDBCDriver");
			connection = DriverManager.getConnection("jdbc:hsqldb:mem:mymemdb", "SA", "");
		} catch (ClassNotFoundException | SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}

	private void createDatabase() {
		Statement statement;
		try {
			statement = connection.createStatement();
			statement.execute(" CREATE TABLE IF NOT EXISTS USUARIOS (ID INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, LOGIN VARCHAR(20), PASSWORD VARCHAR(20))");
			if(!statement.executeQuery("SELECT * FROM USUARIOS").next()) {
				statement.execute("INSERT INTO USUARIOS (LOGIN, PASSWORD) VALUES ('root','1234')");
			}
		} catch (SQLException e) {
			e.printStackTrace();
		}		
	}
	
	
	public Connection getConnection() {
		return connection;
	}
	
	public void close() {
		try {
			connection.close();
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		connection = null;
		instance = null;
	}
	

}
